### ISSUE TITLE
Memory Error in print_trace

### ISSUE THREAD

**Issue by lks9** [lks9/src-tracer#28]
When trying to open a large trace file (30 GB) I am getting a memory error:

```
$ python print_trace.py 2023-05-04-000230-appletlib.c.trace
Traceback (most recent call last):
  File "print_trace.py", line 28, in <module>
    trace = Trace.from_file(trace_file)
  File "src_tracer/trace.py", line 51, in from_file
    trace_bytes = f.read()
MemoryError
```

**Comment by lks9** [comment]
Solved with f665f49b3c7f4d28dcb6b50ce5645b958973f634.

**Comment by lks9** [comment]
Now I know how to solve the error by using `mmap` like in `find_in_trace.py`. However, it's not yet implemented in `src_tracer/trace.py`.

**Comment by ducorduck** [comment]
Should i just replace read with the appropriate one from mmap? 

Also I don't have a big trace so I can't recreate the bug.

**Comment by ducorduck** [comment]
i've done just that in the `mmap_trace` branch i've just created. Could you try it out?

**Comment by lks9** [comment]
Sorry, this week I am on vacation and I don't have that 30 G file with me.

Maybe you can just create such a file yourself, by recording a loop? The C program can be very simple and the recording should be streight forward.

**Comment by ducorduck** [comment]
I've added [bigTrace.c](https://github.com/lks9/src-tracer/blob/main/examples/bigTrace.c) to test this issue.
This give a 10gb compact trace or 14gb text trace, because i only have 8gb of ram so it's enough to encounter the error for me.
I've tested my implementation and it works.
If you want a bigger trace you could change the variable `numGb` to your like (10 is the default value). Just a note, the runtime for the text trace is a lot longer (about 10x) than the compact trace on this program.
